[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  base = "front"
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.19.5"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps"